//! Build script for icon embedding
//!
//! Generates icon constants in OUT_DIR with all icons embedded via include_str!

use std::collections::BTreeMap;
use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let icons_dir = Path::new(&manifest_dir).join("assets/icons");
    let out_file = Path::new(&out_dir).join("icons.rs");

    // Only regenerate if icons changed
    println!("cargo:rerun-if-changed=assets/icons");

    // Collect all SVG files
    let mut icons: BTreeMap<String, String> = BTreeMap::new();

    if let Ok(entries) = fs::read_dir(&icons_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "svg")
                && let Some(stem) = path.file_stem().and_then(|s| s.to_str())
            {
                // Convert filename to valid Rust identifier
                let mut ident = stem.replace(['-', '.'], "_").to_uppercase();
                // Prefix with underscore if starts with digit
                if ident.chars().next().is_some_and(|c| c.is_ascii_digit()) {
                    ident = format!("_{}", ident);
                }
                let abs_path = icons_dir.join(format!("{}.svg", stem));
                icons.insert(ident, abs_path.display().to_string());
            }
        }
    }

    // Generate the module
    let mut out = File::create(&out_file).expect("Failed to create icons.rs in OUT_DIR");

    writeln!(out, "// Auto-generated icon embeddings").unwrap();
    writeln!(out, "// Generated by build.rs from assets/icons/").unwrap();
    writeln!(out, "// Do not edit manually.").unwrap();
    writeln!(out).unwrap();

    // Write constants
    for (ident, path) in &icons {
        writeln!(
            out,
            "pub const {}: &str = include_str!(\"{}\");",
            ident, path
        )
        .unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "/// Total number of embedded icons").unwrap();
    writeln!(out, "pub const ICON_COUNT: usize = {};", icons.len()).unwrap();

    println!("cargo:info=Generated {} icon constants", icons.len());
}
