//! Footer component for all pages

use maud::{Markup, html};

/// Renders page footer with Gitkyl attribution link
///
/// This footer appears consistently across all page types (index, blob, tree,
/// commits) providing a single source of truth for the attribution markup.
pub fn footer() -> Markup {
    html! {
        footer {
            p {
                "Generated by "
                a href="https://github.com/lemorage/gitkyl" target="_blank" { "Gitkyl" }
            }
        }
    }
}
